# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: beb00d8877f4537117b3f532548ada4d7466662bba12fef59b90eabac09075d92fcd65d4115867de74039f8d79e82cf7a027b7877176d7d68ad33cb7cdd3e840

test:
  secret_key_base: 130056a924f401b37daeeeb1a7596b7d568c8c74258f61ffe88fb331be6e6506436b12c0eba1f5a9cfe03a81b8f0907c3e88c002c2aa5f4fa14ba29315737a61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
